#!/usr/bin/env python3
"""
SENSE: Sensemaking Evaluation via NLI and Semantic Entailment
PAN@CLEF 2026 Sensemaking Task - TIRA Inference Pipeline

Architecture:
  1. Irish answer translation (Helsinki-NLP/opus-mt-ga-en)
  2. V3 feature extraction (SBERT + NLI cross-encoder + lexical)
  3. CES subscore computation
  4. Fine-tuned DeBERTa CORAL cross-encoder
  5. LightGBM + MLP ensemble
  6. Product of Experts (PoE) combination via KDE

Pre-trained models must be in models/tira/ (generated by train.py).

Usage (TIRA):
    python predict.py -i /path/to/input -o /path/to/output
"""

import os
import sys
import json
import time
import argparse
import gc
import logging
import warnings

import numpy as np

warnings.filterwarnings('ignore')

import torch

_FORCE_CPU = os.environ.get('SENSE_FORCE_CPU', '0') == '1'
if _FORCE_CPU:
    torch.backends.mps.is_available = lambda: False

from torch.utils.data import DataLoader
from tqdm import tqdm
from transformers import AutoTokenizer
from sentence_transformers import SentenceTransformer, CrossEncoder

from sense.models import DeBERTaRubricScorer, RubricDataset, SimpleDataset, dynamic_collate_fn
from sense.features import FeatureExtractor
from sense.ces import compute_ces_features, compute_simple_ces_features
from sense.ensemble import (
    score_to_probs_kde_perclass,
    safe_probs,
    retrieval_score,
)
from sense.translate import detect_irish, translate_items
from sense.io import load_input_data, write_output, detect_track, load_models

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[logging.StreamHandler(sys.stderr)]
)
logger = logging.getLogger(__name__)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(SCRIPT_DIR, 'models', 'tira')


def main():
    parser = argparse.ArgumentParser(description='SENSE: Sensemaking Evaluation System')
    parser.add_argument('-i', '--input', required=True, help='Input directory')
    parser.add_argument('-o', '--output', required=True, help='Output directory')
    parser.add_argument('--model-dir', default=MODEL_DIR, help='Model directory')
    parser.add_argument('--device', default='cpu', help='Inference device (cpu, mps, cuda)')
    parser.add_argument('--debug', action='store_true')
    args = parser.parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    start_time = time.time()
    logger.info("=" * 60)
    logger.info("SENSE: Sensemaking Evaluation via NLI + Semantic Entailment")
    logger.info("PAN@CLEF 2026 - TIRA Inference Pipeline")
    logger.info("=" * 60)

    model_dir = args.model_dir
    logger.info(f"Loading models from {model_dir}/...")

    samples = load_input_data(args.input)

    track, n_classes = detect_track(samples)
    logger.info(f"Detected track: {track} ({n_classes} classes)")

    models = load_models(model_dir, track, n_classes)

    lgb_models = models['lgb_models']
    mlp_models = models['mlp_models']
    scaler = models['scaler']
    poe_weights = models['poe_weights']
    train_deberta_scores = models['train_deberta_scores']
    train_combo_scores = models['train_combo_scores']
    train_labels = models['train_labels']
    kde_bandwidths = models['kde_bandwidths']
    n_features = models['n_features']
    train_answer_embs = models['train_answer_embs']
    train_question_keys = models['train_question_keys']
    retrieval_sigma = models['retrieval_sigma']
    language_calibration = models['language_calibration']
    deberta_model_configs = models['deberta_model_configs']
    deberta_model_weights = models['deberta_model_weights']

    w_db, w_combo, w_ret = poe_weights

    # Load SBERT and NLI
    logger.info("  Loading SBERT model...")
    sbert = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')
    logger.info("  Loading NLI model...")
    nli = CrossEncoder('cross-encoder/nli-deberta-v3-base', max_length=512)

    extractor = FeatureExtractor(sbert, nli)
    logger.info("  All models loaded.")

    # Translate Irish items
    logger.info("Checking for Irish items...")
    samples_translated = translate_items(samples)

    # Extract features (track-specific)
    logger.info(f"Extracting {track} track features...")
    if track == 'simple':
        X_v3 = extractor.extract_simple_features(samples_translated, verbose=True)
        ces = compute_simple_ces_features(X_v3)
    else:
        X_v3 = extractor.extract_dataset_features(samples_translated, verbose=True)
        ces = compute_ces_features(X_v3)
    X_full = np.hstack([ces, X_v3])
    logger.info(f"CES + V3 features: {X_full.shape}")

    # Compute SBERT embeddings for retrieval (rubric track only)
    ret_probs = None
    if track == 'rubric' and train_answer_embs is not None:
        logger.info("Computing SBERT embeddings for retrieval...")
        answers_for_emb = [s.get('input', s).get('answer', '') for s in samples_translated]
        test_embs = sbert.encode(answers_for_emb, batch_size=64, show_progress_bar=True)
        test_embs_norm = test_embs / (np.linalg.norm(test_embs, axis=1, keepdims=True) + 1e-10)

        pool_items = [{'input': {'rubrics': {'FC': k}}} for k in train_question_keys]
        ret_probs, ret_raw = retrieval_score(
            samples_translated, test_embs_norm,
            pool_items, train_answer_embs, train_labels,
            sigma=retrieval_sigma, exclude_self=False
        )
        ret_features = np.hstack([ret_probs, ret_raw.reshape(-1, 1)])
        X_full = np.hstack([X_full, ret_features])
        logger.info(f"Added retrieval features: {X_full.shape}")

    if X_full.shape[1] != n_features:
        raise ValueError(f"Feature count mismatch: got {X_full.shape[1]}, expected {n_features}. "
                         f"Ensure models were trained with the same feature extraction pipeline.")

    # Free SBERT/NLI memory
    del sbert, nli, extractor
    gc.collect()

    # DeBERTa inference (load one model at a time to save memory)
    device = torch.device(args.device)
    logger.info(f"Running DeBERTa inference ({len(deberta_model_configs)} model(s)) on {device}...")
    DatasetClass = SimpleDataset if track == 'simple' else RubricDataset
    all_model_scores = []
    for m_idx, (model_name, model_path) in enumerate(deberta_model_configs):
        with open(os.path.join(model_path, 'config.json')) as f:
            cfg = json.load(f)
        mname = cfg['model_name']
        logger.info(f"  Loading model {m_idx}: {mname}...")
        tok = AutoTokenizer.from_pretrained(mname)
        dmodel = DeBERTaRubricScorer(mname, cfg['n_classes'], cfg['dropout'])
        dmodel.load_state_dict(
            torch.load(os.path.join(model_path, 'model.pt'), map_location='cpu', weights_only=True)
        )
        dmodel.float()
        dmodel.to(device)
        dmodel.eval()

        dataset = DatasetClass(samples_translated, tok, max_length=512)
        loader = DataLoader(dataset, batch_size=32, shuffle=False, num_workers=0,
                            collate_fn=dynamic_collate_fn)
        scores_this = []
        with torch.no_grad():
            for batch in tqdm(loader, desc=f"DeBERTa model {m_idx+1}/{len(deberta_model_configs)}"):
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                logits = dmodel(input_ids, attention_mask)
                scores = dmodel.coral_head.predict_scores(logits)
                scores_this.extend(scores.cpu().numpy())
        scores_arr = np.array(scores_this)
        logger.info(f"  Model {m_idx}: range=[{scores_arr.min():.3f}, {scores_arr.max():.3f}]")
        all_model_scores.append(scores_arr)

        del dmodel, tok, dataset, loader
        gc.collect()

    if deberta_model_weights is not None and len(deberta_model_weights) == len(all_model_scores):
        deberta_scores = np.average(all_model_scores, axis=0, weights=deberta_model_weights)
    else:
        deberta_scores = np.mean(all_model_scores, axis=0)
    logger.info(f"DeBERTa ensemble scores: range=[{deberta_scores.min():.3f}, {deberta_scores.max():.3f}]")

    # LGB + MLP inference
    logger.info("Running LGB + MLP inference...")
    lgb_preds = np.zeros(len(samples))
    for m in lgb_models:
        lgb_preds += m.predict(X_full)
    lgb_preds /= len(lgb_models)

    X_scaled = scaler.transform(X_full)
    mlp_preds = np.zeros(len(samples))
    for m in mlp_models:
        mlp_preds += m.predict(X_scaled)
    mlp_preds /= len(mlp_models)

    combo_scores = (lgb_preds + mlp_preds) / 2

    # PoE combination with per-class KDE
    logger.info("Combining predictions via PoE (per-class KDE)...")
    db_probs = safe_probs(score_to_probs_kde_perclass(
        deberta_scores, train_deberta_scores, train_labels, kde_bandwidths, n_classes))
    combo_probs = safe_probs(score_to_probs_kde_perclass(
        combo_scores, train_combo_scores, train_labels, kde_bandwidths, n_classes))

    if w_ret > 0 and ret_probs is not None:
        ret_probs_safe = safe_probs(ret_probs)
        log_p = (w_db * np.log(db_probs + 1e-10) +
                 w_combo * np.log(combo_probs + 1e-10) +
                 w_ret * np.log(ret_probs_safe + 1e-10))
    else:
        log_p = w_db * np.log(db_probs + 1e-10) + w_combo * np.log(combo_probs + 1e-10)
    combined = np.exp(log_p)
    combined /= combined.sum(axis=1, keepdims=True)
    final_labels = np.argmax(combined, axis=1)

    # Apply per-language KDE calibration overrides
    if language_calibration and track == 'rubric':
        for lang_code, lang_cal in language_calibration.items():
            lang_indices = [i for i, s in enumerate(samples)
                           if (detect_irish(s) if lang_code == 'ga'
                               else s.get('lang') == lang_code)]
            if not lang_indices:
                continue
            logger.info(f"  Applying {lang_code} calibration to {len(lang_indices)} items...")
            lang_bws = lang_cal['kde_bandwidths']
            lang_poe = lang_cal.get('poe_weights', poe_weights)
            lw_db, lw_combo = lang_poe[0], lang_poe[1]
            lw_ret = lang_poe[2] if len(lang_poe) > 2 else 0.0

            li = np.array(lang_indices)
            lang_db_probs = safe_probs(score_to_probs_kde_perclass(
                deberta_scores[li], train_deberta_scores, train_labels, lang_bws, n_classes))
            lang_combo_probs = safe_probs(score_to_probs_kde_perclass(
                combo_scores[li], train_combo_scores, train_labels, lang_bws, n_classes))

            if lw_ret > 0 and ret_probs is not None:
                lang_ret_safe = safe_probs(ret_probs[li])
                lang_log_p = (lw_db * np.log(lang_db_probs + 1e-10) +
                              lw_combo * np.log(lang_combo_probs + 1e-10) +
                              lw_ret * np.log(lang_ret_safe + 1e-10))
            else:
                lang_log_p = (lw_db * np.log(lang_db_probs + 1e-10) +
                              lw_combo * np.log(lang_combo_probs + 1e-10))
            lang_combined = np.exp(lang_log_p)
            lang_combined /= lang_combined.sum(axis=1, keepdims=True)
            final_labels[li] = np.argmax(lang_combined, axis=1)

    # Build output
    predictions = []
    for i, sample in enumerate(samples):
        predictions.append({
            "id": sample.get("id", sample.get("uid", str(i))),
            "label": int(final_labels[i])
        })

    write_output(args.output, predictions)

    elapsed = time.time() - start_time
    logger.info(f"Completed {len(samples)} samples in {elapsed:.1f}s "
                f"({elapsed / max(len(samples), 1):.2f}s/sample)")
    logger.info("Done!")


if __name__ == '__main__':
    main()
